name: Submit A Bug Report
title: Bug Report
description: Help Improve the Cobble Deez server
projects: []
labels:
  - bug
assignees: Crazyminer34
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: Describe the issue
    validations:
      required: true
  - type: textarea
    id: textarea-1
    attributes:
      label: "Steps to Reproduce:"
  - type: textarea
    id: textarea-2
    attributes:
      label: Additional Context
    validations:
      required: false
  - type: textarea
    id: textarea-3
    attributes:
      label: Screenshots (if aplicable)
      description: Paste your screenshots here
    validations:
      required: false
  - type: checkboxes
    id: checkboxes-4
    attributes:
      label: Issue type
      description: A client side issue may be textures, crashes, or weird behavior,
        serverside is literally anything else
      options:
        - label: This is a client side issue
        - label: This is a server side issue
    validations:
      required: true

